home-server/home/home/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from main.views import index
from orders.views import yookassa_webhook_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('yookassa/webhook/', yookassa_webhook_view),
    path('home/', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home-server/home/orders/urls.py
from django.urls import path

from orders.views import create_order

app_name = 'orders'

urlpatterns = [
    path('order-create/', create_order, name='create'),
]

home-server/home/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required


from users.views import UserLoginView, UserProfileView, UserRegistrationView, cart_page, email_verification_view

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', login_required(LogoutView.as_view()), name='logout'),
    path('registration/', UserRegistrationView.as_view(), name='register'),
    path('profile/<int:pk>', login_required(UserProfileView.as_view()), name='profile'),
    path('cart/', login_required(cart_page), name='user_cart'),
    path('verification/<str:email>/<uuid:code>/', email_verification_view, name='verify'),
]

home-server/home/users/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail

from django.contrib.auth.models import AbstractUser

from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    
    email = models.EmailField(_("email address"), blank=True, unique=True)
    image = models.ImageField(upload_to='users_images', blank=True, null=True)
    is_verified = models.BooleanField(default=False)


class EmailVerification(models.Model):

    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'EmailVerification for {self.user.username}'
    
    def is_expired(self):
        return now() >= self.expiration
    
    def send_verification_email(self):
        
        link = reverse('users:verify', kwargs={'email': self.user.email, 'code': self.code})
        verification_url = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Спасибо за регистрацию на сайте {}!\n\
            Для подтверждения учетной записи для {} перейдите по ссылке: {}.\n\
            Ссылка активна первые 15 минут после отправки сообщения.'.format(
            settings.DOMAIN_NAME,
            self.user.username,
            verification_url
        )

        send_mail(
            subject,
            message,
            settings.EMAIL_HOST_USER,
            [self.user.email],
            fail_silently=False,
        )

home-server/home/users/forms.py
from typing import Any

from django import forms

from django.utils.translation import gettext_lazy as _

from django.core.exceptions import ValidationError

from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from users.models import User
from users.tasks import send_email_task




class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()


    error_messages = {
        "invalid_login": _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        "inactive": _("This account is inactive."),
        "is_not_veryfied":_("This account is not verifyed. Check your email."),
    }


    def confirm_login_allowed(self, user):

        if not user.is_verified:
            raise ValidationError(
                self.error_messages["is_not_veryfied"],
                code="is_not_veryfied",
            )

        if not user.is_active:
            raise ValidationError(
                self.error_messages["inactive"],
                code="inactive",
            )


    class Meta:

        model = User
        fields = ('username','password')


class UserProfileForm(UserChangeForm):

    image = forms.ImageField()

    first_name = forms.CharField()

    last_name = forms.CharField()

    username = forms.CharField(required=False)

    email = forms.EmailField(required=False)


    class Meta:

        model = User
        fields = ('image','first_name','last_name')



class UserRegistrationForm(UserCreationForm):

    first_name = forms.CharField()

    last_name = forms.CharField()

    username = forms.CharField()

    email = forms.EmailField()

    password1 = forms.CharField()

    password2 = forms.CharField()


    class Meta:

        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')



    def save(self, commit: bool = ...) -> Any:

        user = super().save(commit)

        send_email_task.delay(user)
    
        return user

home-server/home/users/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth import login as auth_login
from django.contrib.messages.views import SuccessMessageMixin

from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect

from django.views.generic.edit import CreateView, UpdateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm

from carts.models import HomeCart
from users.models import User, EmailVerification
from carts.models import HomeCart



class UserLoginView(TitleMixin, LoginView):

    template_name = "users/login.html"
    form_class = UserLoginForm
    title = 'Home - Авторизация'

    def post(self, request, *args, **kwargs):

        form = self.get_form()
        if form.is_valid():
            self.session_key = request.session.session_key
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        

    def form_valid(self, form):
        
        user = form.get_user()
        auth_login(self.request, user)

        if self.session_key:
            HomeCart.objects.filter(session_key=self.session_key).update(user=user)
        
        return HttpResponseRedirect(self.get_success_url())



class UserProfileView(TitleMixin, UpdateView):

    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'Home - Личный кабинет'

    def get_success_url(self):

        return reverse_lazy('users:profile', args=(self.object.id,))
    
    def get(self, request, *args, **kwargs):

        self.object = self.get_object()
        if request.user == self.object:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseBadRequest(status=404)
        
    def post(self, request, *args, **kwargs):
        
        self.object = self.get_object()
        if request.user == self.object:
            return super().post(request, *args, **kwargs)
        else:
            return HttpResponseBadRequest(status=404)

    

class UserRegistrationView(SuccessMessageMixin, TitleMixin, CreateView):

    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    title = 'Home - Регистрация'
    success_url = reverse_lazy('users:login')
    success_message = 'Для окончания регистрации, перейдите по ссылке, отправленной вам на почту!'





def cart_page(request):

    context = {'title': 'Home - Корзина'}

    return HttpResponse(render(request, 'carts/user_basket.html', context))


def email_verification_view(request, email, code):
    
    if request.method == 'GET':

        user = User.objects.get(email=email)
        verification = EmailVerification.objects.get(code=code)
        if verification.is_expired() or not verification.active:

            messages.warning(request, 'Данная ссылка неактивна!')
            return redirect('main:index')
        
        else:

            session_key = request.session.session_key
            auth_login(request, user)

            verification.active = False
            verification.save()

            if session_key:
                HomeCart.objects.filter(session_key=session_key).update(user=user)

            messages.success(request, 'Ваша почта верифицирована!')
            return redirect('main:index')

home-server/home/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block basket %}{% endblock basket %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url 'users:login' %}" method='POST'>
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" name="username" id="id_username" placeholder="Введите ваше имя пользователя">
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" name="password" id="id_password" placeholder="Введите ваш пароль">
                        </div>
                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Забыли пароль?</a> | <a href={% url "users:register" %}>Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static '/deps/icons/google.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static '/deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static '/deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home-server/home/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}


{% block basket %}{% endblock basket %}


{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Ваш профиль</h3>
                        <form action="{% url "users:profile" user.id %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    <img src="{% if user.image %}{{ user.image.url }}{% else %}{% static '/deps/images/baseavatar.jpg' %}{% endif %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px;">
                                        <input type="file" class="form-control mt-3" name="image" id="id_image"
                                        accept="image/*">
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">Имя*</label>
                                    <input type="text" class="form-control" name='first_name' id="id_first_name"
                                    placeholder="Введите ваше имя" value="{% if user.first_name %}{{ user.first_name }}{% endif %}">
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Фамилия*</label>
                                    <input type="text" class="form-control" name="last_name" id="id_last_name"
                                    placeholder="Введите вашу фамилию" value="{% if user.last_name %}{{ user.last_name }}{% endif %}">
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Имя пользователя*</label>
                                    <input type="text" class="form-control" name="username" id="id_username"
                                    placeholder="Ваше имя пользователя" value="{{user.username}}" disabled> 
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" name="email" id="id_email"
                                    placeholder="Введите ваш email *youremail@example.com" value="{{ user.email }}" disabled>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                    </div>
                </div>
                <!-- Корзина -->
                <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Корзина</h3>
                        {% include "carts\includes\included_cart.html" %}
                        <a class="btn btn-dark" href="{% url "orders:create" %}">
                            Оформить заказ
                        </a> 
                    </div>
                </div>
                <!-- Оформленные заказы -->
                {% include "orders\includes\included_orders.html" %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}{% endblock footer %}

home-server/home/users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}


{% block basket %}{% endblock basket %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action={% url "users:register" %} method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" name="first_name" id="id_first_name"
                                    placeholder="Введите ваше имя" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" name="last_name" id="id_last_name"
                                    placeholder="Введите вашу фамилию" value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" required>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" name="username" id="id_username"
                                    placeholder="Введите ваше имя пользователя" required>
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" name="email" id="id_email"
                                    placeholder="Введите ваш email" required>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" name="password1" id="id_password1"
                                    placeholder="Введите пароль" required>
                                {% if form.password1.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" name="password2" id="id_password2"
                                    placeholder="Подтвердите пароль" required>
                                {% if form.password2.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}