home-server/home/home/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from main.views import index
from orders.views import yookassa_webhook_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('yookassa/webhook/', yookassa_webhook_view),
    path('home/', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home-server/home/orders/urls.py
from django.urls import path

from orders.views import create_order

app_name = 'orders'

urlpatterns = [
    path('order-create/', create_order, name='create'),
]

home-server/home/orders/models.py
from django.db import models

from users.models import User
from goods.models import Products


class OrderItemQuerySet(models.QuerySet):

    def total_price(self):

        return sum(order.product_price() for order in self)
    
    def total_quantity(self):

        return sum(order.quantity for order in self)
    

class Order(models.Model):

    CREATED = 0
    ON_WAY = 1
    DELIVERED = 2
    RECEIVED = 3

    STATUSES = (
        (CREATED, 'In processing'),
        (ON_WAY, 'On way'),
        (DELIVERED, 'Delivered'),
        (RECEIVED,'Received'),
    )

    user = models.ForeignKey(to=User, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Order owner')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Date of create')
    phone_number = models.CharField(max_length=20, default=False, verbose_name='Phone number')
    requires_delivery = models.BooleanField(verbose_name='Delivery')
    delivery_address = models.TextField(null=True, blank=True, verbose_name='Delivery address')
    payment_on_get = models.BooleanField(default=False, verbose_name='Pay on get')
    is_paid = models.BooleanField(default=False, verbose_name='Order is paid')
    status = models.PositiveSmallIntegerField(default=CREATED, choices=STATUSES, verbose_name='Order status')


    class Meta:

        verbose_name_plural = 'Orders'


    def __str__(self) -> str:
        return f'Order №{self.pk} | Purchaser - {self.user.username}'

    
class OrderItem(models.Model):

    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Order')
    product = models.ForeignKey(to=Products, null=True, on_delete=models.SET_NULL, verbose_name='Product')
    name = models.CharField(max_length=150, verbose_name='Product name')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Price')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Quantity')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Date of create')

    objects = OrderItemQuerySet.as_manager()


    class Meta:

        verbose_name = 'Sold item'
        verbose_name_plural = 'Sold items'
    
    def __str__(self) -> str:
        return f"Order №{self.order.pk} | Product - {self.product.name}"

    
    def product_price(self):
        return round(self.price * self.quantity, 2)

home-server/home/orders/forms.py
from django import forms
import re

class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(choices=[
        ('0', False),
        ('1', True)
    ])
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(choices=[
        ('0', False),
        ('1', True)
    ])


    def clean_phone_number(self):
        data = self.cleaned_data["phone_number"]

        if not data.isdigit():
            raise forms.ValidationError('The phone number must contain only numbers!')
        
        pattern = re.compile(r'^7\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError('The phone number is invalid!')
        
        return data
    
    def clean_delivery_address(self):
        data = self.cleaned_data["delivery_address"]
        
        requires_delivery = self.cleaned_data['requires_delivery'] == '1'
        if requires_delivery and not data:
            raise forms.ValidationError('This field cannot be empty at this time!')

        # TODO handler coordinates with google maps api

        return data
    
    

home-server/home/orders/views.py
import json
import uuid
from django.db import transaction

from django.forms import ValidationError

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.conf import settings

from yookassa import Configuration, Payment

from carts.utils import get_user_carts

from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem


@login_required
def create_order(request):
    
    user_carts = get_user_carts(request)
    user = request.user

    if request.method == 'POST':

        form = CreateOrderForm(data=request.POST)

        if form.is_valid():
            try:
                with transaction.atomic():
                    if user_carts.exists():
                        
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'], 
                        )

                        for user_cart in user_carts:
                            product = user_cart.product
                            name = user_cart.product.name
                            price = user_cart.price
                            quantity = user_cart.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f"Insufficient quantity of '{name}' in stock. \
                                                        In stock - {product.quantity}")
                            
                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )

                            product.quantity -= quantity
                            product.save()

                        # Если оплата картой, редирект на юкассу
                        if form.cleaned_data['payment_on_get'] == '0':

                            payment = Payment.create({
                                "amount": {
                                    "value":user_carts.total_price(),
                                    "currency": "RUB" #не могу USD поставить изза account.gateway_id юкассы
                                },
                                "confirmation": {
                                    "type": "redirect",
                                    "return_url": "{}:8000{}".format(settings.DOMAIN_NAME, reverse('users:profile', kwargs={'pk':user.id}))
                                },
                                "capture": True,
                                "description": f"Заказ в Home #{order.id}",
                                'metadata': {
                                    'order_id': order.id
                                }
                            }, uuid.uuid4())

                            user_carts.delete()
                            return HttpResponseRedirect(payment.confirmation.confirmation_url)

                        user_carts.delete()
                        messages.success(request, 'Заказ оформлен!')
                        return redirect('users:profile', pk=user.id)
                    
            except ValidationError as e:
                messages.warning(request, str(e))
                return redirect('users:profile', pk=user.id)
    
            
        else:
            context = {'title': 'Home - Новый заказ', 'form': form}

            return render(request, 'orders/create_order.html', context)


        
    elif request.method == 'GET':

        if not user_carts.exists():
            
            messages.warning(request, f"Вы не можете оформить заказ, пока корзина пуста!")

            return redirect(to='goods:catalog', slug='all')

        
        else:

            init = {
                'first_name': user.first_name,
                'last_name': user.last_name
            }

            form = CreateOrderForm(initial=init)

            context = {'title': 'Home - Новый заказ', 'form': form}

            return render(request, 'orders/create_order.html', context)
        


Configuration.account_id = settings.YOKASSA_ACC_ID
Configuration.secret_key = settings.YOKASSA_SECRET
@csrf_exempt
def yookassa_webhook_view(request):

    payload = request.body.decode('utf-8')
    payload_dict = json.loads(payload)
    if payload_dict ['object']['status'] == 'succeeded':

        order_id = order_id = int(payload_dict['object']['metadata']['order_id'])
        order = Order.objects.get(id=order_id)
        order.is_paid = True
        order.save()

    elif payload_dict ['object']['status'] == 'canceled':

        # some func if pay canceled
        ...

    return HttpResponse(status=200)

home-server/home/orders/templates/orders/create_order.html
{% extends "base.html" %}

{% load static %}


{% block basket %}{% endblock basket %}

{% block content %}
    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
        <div class="container">
            <h3 class="text-center mb-4">Выбранные товары</h3>
            {% include "carts\includes\included_cart.html" %}
        </div>
        <!-- Детали заказа -->
        <div class="container">
            <h3 class="text-center">Детали заказа</h3>
            <div class="card mb-3">
                <div class="card-body">
                    <form action="{% url "order:create" %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*:</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*:</label>
                                <input type="text" class="form-control" id="id_last_name" name="last_name" 
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" required>
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_phone_number" class="form-label">Номер телефона*:</label>
                                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                    placeholder="В формате: 79123456789"
                                    value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                    required>
                                {% if form.phone_number.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="delivery" class="form-label">Способ доставки: </label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                        id="id_requires_delivery" value="1" checked>
                                    <label class="form-check-label" for="id_requires_delivery">Нужна
                                        доставка</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                        id="id_requires_delivery" value="0">
                                    <label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
                                </div>
                            </div>
                            <div class="mb-3" id="deliveryAddressField">
                                <label for="id_delivery_address" class="form-label">Адрес
                                    доставки*:</label>
                                <textarea class="form-control" id="id_delivery_address"
                                    name="delivery_address" rows="2"></textarea>
                                {% if form.delivery_address.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Способ оплаты: </label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                        id="id_payment_on_get" value="0" checked>
                                    <label class="form-check-label" for="id_payment_on_get">Оплата
                                        картой</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                        id="id_payment_on_get" value="1">
                                    <label class="form-check-label" for="id_payment_on_get">Наличными/картой
                                        при пoлучении</label>
                                </div>
                                {% if form.payment_on_ge.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.payment_on_ge.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Оформить заказ</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}