2engine/app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('rest_api.urls', namespace='api')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

2engine/app/rest_api/urls.py
from django.urls import path
from rest_framework import routers
from .views import TasksListViewSet, TaskViewSet

app_name = 'rest_api'

router = routers.SimpleRouter()
router.register(r'task', TaskViewSet)

urlpatterns = [
    path('list-tasks/', TasksListViewSet.as_view({'get':'list'})),
]

urlpatterns += router.urls

2engine/app/tasks/urls.py
from django.urls import path

from .views import TasksListView

app_name = 'tasks'

urlpatterns = [
    path('list/', TasksListView.as_view(), name='list')
]

2engine/app/tasks/models.py
from typing import Iterable
from django.db import models

class Task(models.Model):

    QUEUE = 0
    IN_PROGRESS = 1
    COMPETED = 2

    STATUSES = (
        (QUEUE, 'Queue.'),
        (IN_PROGRESS, 'In progress...'),
        (COMPETED, 'Completed!'),
    )

    name = models.CharField(max_length=150, verbose_name='Task name')
    description = models.TextField(blank=True, null=True, verbose_name='Description')
    status = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Status', default=QUEUE, choices=STATUSES)

    class Meta:

        verbose_name_plural = 'Tasks'


    def __str__(self) -> str:
        return self.name

    

2engine/app/common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        context["title"] = self.title
        return context

2engine/app/rest_api/views.py
from rest_framework import viewsets, status, mixins, response
from rest_framework.response import Response

from tasks.serializers import TaskSerializer, Task

from tasks.tasks import process

class TaskViewSet(viewsets.ModelViewSet):

    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    def list(self, request):
        
        return Response(data={'errors': 'This method now allowed! Use another endpoint.'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)
    
    def create(self, request, *args, **kwargs):

        data= request.data.dict()
        serializer = self.get_serializer(data=data)

        if serializer.is_valid():

            task = serializer.save(**data)
            process.delay(task.id)

            return response.Response(data=serializer.data, status=status.HTTP_201_CREATED)

        return response.Response(data={"errors":serializer.errors}, status=status.HTTP_400_BAD_REQUEST)


class TasksListViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):

    queryset = Task.objects.all()
    serializer_class = TaskSerializer

2engine/app/tasks/views.py
from django.views.generic.list import ListView

from .models import Task

from common.views import TitleMixin

from .utils import q_search


class TasksListView(TitleMixin, ListView):

    model = Task
    template_name = "tasks/index.html"
    title = 'Tasks List'
    paginate_by = 15

    def get_queryset(self):
        
        queryset = super().get_queryset()

        params = self.request.GET
        query = params.get('q')
        
        if query:
            queryset = q_search(query)

        return queryset

2engine/app/templates/tasks/index.html
{% load static %}

{% load query_transform  %}

<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'deps/css/reset.css' %}" rel="stylesheet" >
    <link rel="stylesheet" href="{% static 'deps/css/styles.css' %}">
    <title>Tasks List</title>
</head>
<header>
    <h1>Тasks Table</h1>
</header>
<body>
    <div class="searcher">
        <form action="{% url 'tasks:list' %}" method="get">
            <label>
                <input type="search" name="q" placeholder="Поиск"></input>
            </label>
            <button type="submit">Поиск</button>
        </form>
    </div>
    <div class="table">
        <div class="table-head">
            <ul class="column-name-list">
                <li>ID</li>
                <li>NAME</li>
                <li>DESCRIPTION</li>
                <li>STATUS</li>
            </ul>
        </div>
        <div>
            {% for task in task_list %}
                <div class="table-row">
                    <ul class="task-data-list">
                        <li>{{ task.id }}</li>
                        <li>{{ task.name }}</li>
                        <li>{{ task.description }}</li>
                        <li>{{ task.get_status_display }}</li>
                    </ul>
                </div>
            {% endfor %}
        </div>
        {% if request.GET.q %}
        <div>
            <a href="{% url 'tasks:list' %}">Показать все задачи</a>
        </div>
        {% endif %}
    </div>

    {% if is_paginated %}
        <nav class="paginator">
            <ul class="page-list">
                <li>
                    <a class="{% if not page_obj.has_previous %} disabled {% endif %}" 
                        href="{% if page_obj.has_previous %} ?{% query_transform page=page_obj.previous_page_number %} {% else %} {% endif %}">
                        <img src="{% static 'deps/img/left.svg'%}" alt="arrow-back">
                    </a>
                </li> 

                {% if page_obj.number|add:'-2' > 0 %}
                    <li><a href="?{% query_transform page=page_obj.number|add:'-2' %}">{{ page_obj.number|add:'-2' }}</a></li>
                {% endif %}
                {% if page_obj.has_previous %}
                    <li><a href="?{% query_transform page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}
                <li><a class="disabled" href="">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li><a href="?{% query_transform page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a></li>
                {% endif %}
                {% if page_obj.number|add:'2' <= page_obj.paginator.num_pages %}
                    <li><a href="?{% query_transform page=page_obj.number|add:'2' %}">{{ page_obj.number|add:'2' }}</a></li>
                {% endif %}

                <li>
                    <a class="{% if not page_obj.has_next %} disabled {% endif %}" 
                    href="{% if page_obj.has_next %} ?{% query_transform page=page_obj.next_page_number %} {% else %} {% endif %}">
                    <img src="{% static 'deps/img/right.svg'%}" alt="arrow-forward">
                </a>
                </li> 
            </ul>
        </nav>
    {% endif %}

</body>
</html>